name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v1
        with:
          pages_threshold: major_outage
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build Artifacts
        run: |
          npm install
          npm run build
          npm run export
          touch out/.nojekyll
      - name: Lint
        run: npm run lint
      - name: Type Check
        run: npm run type-check
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
          fqdn: adriandelisle.dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
